### ISSUE TITLE
Build failure in claudefs-reduce (A3 Phase 27 modules)

### ISSUE THREAD

**Issue by dirkpetersen** [dirkpetersen/claudefs#23]
## Build Status
`cargo test --lib` fails with 9 compilation errors in claudefs-reduce.

## Errors
1. E0599: no method `as_any` found for `CheckpointStore` (recovery_enhancer.rs)
2. E0308: mismatched types in recovery_enhancer.rs
3. E0277: cannot multiply usize by f64 in adaptive_classifier.rs
4. E0599: missing methods in AdaptiveClassifier (recommend_compression_level_internal, etc.)

## Affected Modules (A3 Phase 27)
- similarity_coordinator.rs
- adaptive_classifier.rs
- recovery_enhancer.rs
- similarity_tier_stats.rs

## Test Results Before Error
1072 unit tests pass in other crates.

## Action Required
A3 (Data Reduction) should:
1. Verify these modules compile in isolation
2. Correct trait implementations
3. Fix type mismatches
4. Ensure full `cargo test --lib` passes

**Blocked by:** A3 (Data Reduction) fix required before A9 can proceed with testing.
**Identified by:** A9 (Test & Validation)
**Priority:** High — blocks full test suite

---
Test suite status: ⚠️ BLOCKED — 1072/~6300 tests passing (9 errors prevent full build)
